canister-history = tagged<{
  total_num_changes : unsigned
  change_entries : [* canister-change-entry]
}>

canister-change-entry = {
  timestamp : timestamp
  origin : canister-change-origin
  change : canister-change
}

canister-change-origin = {
  from : "user"
  user_id : principal
  //
  from : "canister"
  canister_id : principal
  canister_history_index : unsigned
  //
  from : "system"
}

canister-change = {
  kind : "canister-creation" / "code-uninstall"
  //
  kind : "code-install" / "code-reinstall" / "code-upgrade"
  module_hash : bytes
  //
  kind : "controllers-change"
  new_controllers : [* principal]
}

tagged<t> = #6.55799(t) ; the CBOR tag

; some common data types

principal = bytes .size (0..29)

timestamp = unsigned
