= Implementation status
:stem: latexmath
:icons: font

The Public Specification is ahead (or behind, or different from) the implementation in various points. Since one goal of this document is to provide the _users_ of these interfaces (e.g. authors of programming language implementations, client libraries) everything they need to know, this section will tell them about all the ways implementation differs from the spec.

By including this document in the repository of the code, users have an easy way of looking up the status quo, even if they have pinned the repository at a specific old state and out-of-band tracking (e.g. tickets) has moved on.

This means:

* Every semantically change to the spec should be accompanyied by a change to this file (preferrably in the same PR).
* Similarly, every change to the implementation that affects the public interface should probably be reflected here – often simply by deleting a bullet point.

The goal of this section is not to be unreasonably buerocratic; the goal is to be _useful_. Not every deviation of the spec might be worth mentioning here. For example: if the implementation is _more_ permissive than the spec in some way, then this may not have to be tracked here. Apply your own judgemnet.

Nothing in this section indicated “approval” of sorts.

Without further ado, here we go:

== HTTP API

* Signatures are not validated

== System API
* `+msg.reply+` and `+msg.reject+` are implemented with different signatures (e.g. no reply data accumulation)
* No inter-canister calls; the system calls `+method.*+` and `+call.*+` cannot even be imported.
* `memory.grow` does not actually grow the memory
* `canister.id` and `canister.lookup` expect `i64` canister ids, rather than https://github.com/dfinity-lab/dfinity/pull/1224[blobs], and don’t have the latest names.
* `msg.arg_data_copy` has the `offset` parameter last, not second-to-last, as it is specified since [the design review](https://docs.google.com/a/dfinity.org/document/d/1V-odGuiXe7IZeUuDEEm8-agSOpSDkveU4bJuBYegt3s/edit?disco=AAAACLAcykA).
* An import `msg.entropy` is allowed; the spec removed this because of uncertainty about the entropy implementation (it might be async)
